const menu = [
  {
    id: 1,
    category: "hot-drinks",
    title: "Tea",
    price: 2.99,
    img: "./img/hot-drinks/tea.jpg",
    desc: `100% Turkish tea, freshly brewed and served in a cup.`,
  },
  {
    id: 2,
    category: "hot-drinks",
    title: "Herbal Tea",
    price: 4.99,
    img: "./img/hot-drinks/herbal-tea.jpg",
    desc: `a mixture of fresh herbs and spices, freshly brewed and served in a cup.`,
  },
  {
    id: 3,
    category: "hot-drinks",
    title: "Turkish Coffee",
    price: 3.99,
    img: "./img/hot-drinks/turkish-coffee.jpg",
    desc: `Turkish coffee is very finely ground coffee brewed by boiling. `,
  },
  {
    id: 4,
    category: "hot-drinks",
    title: "Latte",
    price: 5.99,
    img: "./img/hot-drinks/latte.jpg",
    desc: `Latte is a coffee drink made with espresso, hot milk and steamed milk foam.`,
  },
  {
    id: 5,
    category: "hot-drinks",
    title: "Mocha",
    price: 5.99,
    img: "./img/hot-drinks/mocha.jpg",
    desc: `Mocha is a coffee drink made with espresso, hot milk, chocolate, and steamed milk foam.`,
  },
  {
    id: 6,
    category: "hot-drinks",
    title: "Espresso",
    price: 3.99,
    img: "./img/hot-drinks/espresso.jpg",
    desc: `Espresso is a coffee drink made by forcing a small amount of nearly boiling water under pressure through finely ground coffee beans.`,
  },
  {
    id: 7,
    category: "iced-drinks",
    title: "Ice Latte",
    price: 5.99,
    img: "./img/ice-drinks/icelatte.png",
    desc: `Ice Latte is a coffee drink made with espresso, cold milk & ice cubes.`,
  },
  {
    id: 8,
    category: "iced-drinks",
    title: "Ice Filter Coffee",
    price: 4.99,
    img: "./img/ice-drinks/iced-filter.jpg",
    desc: `Ice Filter Coffee is a coffee drink made with espresso and cold water`,
  },
  {
    id: 9,
    category: "iced-drinks",
    title: "Ice Mocha",
    price: 5.99,
    img: "./img/ice-drinks/ice-mocha.jpg",
    desc: `Ice mocha is a coffee drink made with espresso, cold milk, chocolate, and ice cubes.`,
  },
  {
    id: 10,
    category: "iced-drinks",
    title: "Frappe",
    price: 5.99,
    img: "./img/ice-drinks/frappe.jpg",
    desc: `Frappe is a greek cold coffee drink made with espresso & cold milk.`,
  },
  {
    id: 11,
    category: "beers",
    title: "Heineken",
    price: 8.99,
    img: "./img/beers/heineken.jpg",
    desc: `Heineken is a beer brewed by the Heineken brewery.`,
  },
  {
    id: 12,
    category: "beers",
    title: "Weihenstephaner",
    price: 8.99,
    img: "./img/beers/weihenstephaner.png",
    desc: `Weihenstephaner is a beer brewed by the Weihenstephaner brewery.`,
  },
  {
    id: 13,
    category: "beers",
    title: "Corona Extra",
    price: 8.99,
    img: "./img/beers/corona.jpg",
    desc: `Corona Extra is a beer brewed by the Corona brewery.`,
  },
  {
    id: 14,
    category: "cocktails",
    title: "Espresso Martini",
    price: 12.99,
    img: "./img/coctails/espresso-martini.jpg",
    desc: `Espresso Martini is a cocktail made with vodka, coffee and sugar.`,
  },
  {
    id: 15,
    category: "cocktails",
    title: "Mojito",
    price: 14.99,
    img: "./img/coctails/mojito.jpg",
    desc: `Mojito is a coctail made with rom, sugar, lime, soda & mint.`,
  },
  {
    id: 16,
    category: "cocktails",
    title: "Vodka Martini",
    price: 13.99,
    img: "./img/coctails/vodkamartini.jpg",
    desc: `Vodka Martini made with vodka, dry vermouth, green olive & lemon zest .`,
  },
  {
    id: 17,
    category: "cocktails",
    title: "Sangria",
    price: 17.99,
    img: "./img/coctails/sangria.jpg",
    desc: `Sangria is a cocktail made with red wine, fresh fruit dices, liquor & orange juice`,
  },
  {
    id: 18,
    category: "cocktails",
    title: "Sex On The Beach",
    price: 15.99,
    img: "./img/coctails/sexonthe.jpg",
    desc: `Sex on the beach  is a coctail made with vodka, peach schnapps, cranberry juice & oranges juice.`,
  },
  {
    id: 19,
    category: "shots",
    title: "B-52",
    price: 10.99,
    img: "./img/shots/b52.jpg",
    desc: `B52 is a shot made with vodka, coffee, sugar & cream.`,
  },
  {
    id: 20,
    category: "shots",
    title: "Jagermeister",
    price: 10.99,
    img: "./img/shots/jager.jpg",
    desc: `Jagermeister is German digestif made with 56 herbs and spices.`,
  },
  {
    id: 21,
    category: "shots",
    title: "Sambuca",
    price: 10.99,
    img: "./img/shots/sambuca.jpg",
    desc: `Sambuca is a sweet, white, bitter, and bitter-sweet liqueur made from the dried fruit of the sambuca tree.`,
  },
  {
    id: 22,
    category: "shots",
    title: "Tequila",
    price: 10.99,
    img: "./img/shots/tequila.jpg",
    desc: `Tequla is a distilled beverage made from the blue agave plant.`,
  },
];
export default menu;
